name: ecg-image-generator
channels:
  - defaults
  - conda-forge
dependencies:
  - pip:
      - absl-py==2.3.1
      - astunparse==1.6.3
      - beautifulsoup4==4.12.2
      - blis==0.7.11
      - cachetools==6.2.1
      - catalogue==2.0.10
      - certifi==2025.10.5
      - chardet==3.0.4
      - click==7.1.2
      - contourpy==1.3.0
      - cycler==0.12.1
      - cymem==2.0.11
      - decorator==5.2.1
      - flatbuffers==25.9.23
      - fonttools==4.60.1
      - gast==0.4.0
      - google-auth==2.42.0
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - grpcio==1.74.0
      - h5py==3.14.0
      - html5lib==1.1
      - idna==2.8
      - imageio==2.9.0
      - imgaug==0.4.0
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - imutils==0.5.4
      - jinja2==3.1.6
      - joblib==1.5.2
      - keras==2.13.1
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - libclang==18.1.1
      - markdown==3.9
      - markupsafe==3.0.3
      - matplotlib==3.9.4
      - murmurhash==1.0.13
      - networkx==3.2.1
      - numpy==1.24.3
      - oauthlib==3.3.1
      - opencv-python==4.6.0.66
      - opt-einsum==3.4.0
      - packaging==25.0
      - pandas==1.4.1
      - pathlib-abc==0.1.1
      - pathy==0.11.0
      - pillow==9.5.0
      - preshed==3.0.10
      - protobuf==4.25.8
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==1.8.2
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pywavelets==1.6.0
      - requests==2.21.0
      - requests-oauthlib==2.0.0
      - rsa==4.9.1
      - scikit-image==0.20.0
      - scikit-learn==1.3.2
      - scipy==1.9.1
      - seaborn==0.12.2
      - shapely==2.0.7
      - six==1.17.0
      - smart-open==6.4.0
      - soupsieve==2.8
      - spacy==3.0.8
      - spacy-legacy==3.0.12
      - srsly==2.5.1
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.13.0
      - tensorflow-estimator==2.13.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==3.1.0
      - thinc==8.0.17
      - threadpoolctl==3.6.0
      - tifffile==2024.8.30
      - tqdm==4.67.1
      - typer==0.3.2
      - typing-extensions==4.5.0
      - urllib3==1.24.3
      - validators==0.18.2
      - wasabi==0.10.1
      - webencodings==0.5.1
      - werkzeug==3.1.3
      - wfdb==3.4.1
      - wrapt==2.0.0
      - zipp==3.23.0
